apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infraai-ingress
  namespace: infraai
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: infraai-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infraai-frontend
                port:
                  number: 80
