apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: postgres-patch.yaml
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: ingress-patch.yaml

configMapGenerator:
  - name: foundry-service-patch
    namespace: infraai
    options:
      disableNameSuffixHash: true
    files:
      - azure_foundry_service.py=../../../backend/app/services/azure_foundry_service.py
      - config.py=../../../backend/app/config.py
      - foundry_analyzer.py=../../../backend/app/services/foundry_analyzer.py
      - chat_service.py=../../../backend/app/services/chat_service.py

images:
  - name: REGISTRY/infraai/backend
    newName: 803103365620.dkr.ecr.ap-south-1.amazonaws.com/infraai/backend
    newTag: latest
  - name: REGISTRY/infraai/frontend
    newName: 803103365620.dkr.ecr.ap-south-1.amazonaws.com/infraai/frontend
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/part-of: infraai-agent
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/environment: dev