apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: postgres-patch.yaml
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: ingress-patch.yaml
  - path: secrets-patch.yaml

images:
  - name: REGISTRY/infraai/backend
    newName: 803103365620.dkr.ecr.ap-south-1.amazonaws.com/infraai/backend
    newTag: latest
  - name: REGISTRY/infraai/frontend
    newName: 803103365620.dkr.ecr.ap-south-1.amazonaws.com/infraai/frontend
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/part-of: infraai-agent
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/environment: dev