apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: infraai
spec:
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-csi         # AKS default CSI storage class
        resources:
          requests:
            storage: 20Gi
